### ISSUE TITLE
[iOS] `GameAuth.isSignedIn` not working after user cancel the `GameAuth.signIn()`

### ISSUE THREAD

**Issue by jiak94** [Abedalkareem/games_services#158]
reproduction steps:

1. call `GameAuth.signIn()`
2. cancel the signing
3. call `GameAuth.isSignedIn` -> the return value is `true`

**Comment by jiak94** [comment]
```dart
return GameAuth.isSignedIn.then((isSignedIn) {
      logger.fine('User is signed in: $isSignedIn');
      if (isSignedIn) {
        return Leaderboards.loadLeaderboardScores(
            iOSLeaderboardID: iosLeaderboardID,
            scope: PlayerScope.global,
            timeScope: TimeScope.allTime,
            maxResults: 10);
      } else {
        logger.fine('User is not signed in. Signing in...');
        return GameAuth.signIn().then((value) {
          logger.fine('Sign in result: $value');
          return Leaderboards.loadLeaderboardScores(
              iOSLeaderboardID: iosLeaderboardID,
              scope: PlayerScope.global,
              timeScope: TimeScope.allTime,
              maxResults: 10);
        });
      }
    });
```

<img width="1330" alt="image" src="https://github.com/Abedalkareem/games_services/assets/4082168/85928d92-3286-4dd1-9879-7677e8a7be1e">

**Comment by Abedalkareem** [comment]
That's odd, We are calling GameKit isAuthenticated method.
``` currentPlayer.isAuthenticated ```

I tried also now and I'm getting the value of currentPlayer.isAuthenticated as true from the native side.

**Comment by theLee3** [comment]
@jiak94 Did you get this issue resolved? I have been unable to reproduce with your steps.

**Comment by theLee3** [comment]
@jiak94 Still unable to replicate on emulator or physical device with multiple iOS versions. It was likely a GameKit issue at the time. I am closing this issue, but please reopen if you experience again.

**Comment by theRealGetman** [comment]
@theLee3 I can reproduce it on `4.0.3` package version. No same reproduction, but on iOS simulator/iphone when user cancel Games Center sign in you are not able to request sign in again.

Steps to reproduce:
1) call `GamesService.signIn()`
2) cancel sign in
3) try to call `GamesService.signIn()` again

As a result if you 'await GamesService.signIn()` - app stuck here, since Future is never completed

**Comment by theLee3** [comment]
@theRealGetman This is in fact an issue with how GameCenter auth works and how it was implemented in the package.

Please try our latest RC by updating the games_services dependency in pubspec.yaml like so:

```yaml
games_services:
  git:
      url: https://github.com/Abedalkareem/games_services.git
      ref: add-player-stream
      path: games_services
```

This update these auth issues and provides a new player stream that makes it easy to listen to auth changes and update the UI & use of games_services calls accordingly.

**Comment by theLee3** [comment]
@theRealGetman Of note, you cannot present the GameCenter auth window on iOS during the same session that it was cancelled. For that reason, an unauthenticated error will be thrown, and you should redirect the user to the GameCenter in device settings for authentication. Once they return to your app, all auth checks and methods will work as expected. If you choose to listen to the new player stream, it will actually update while the app is in the background.

**Comment by theRealGetman** [comment]
@theLee3 thanks for your response!

Yeah, I know that we should not call GameCenter auth twice in a session, I just think that it can be handled by the package and throw an error if it has been already called. It would be better than just not finished Future imho :) 

Streams is a great solution, thanks, I'll try it! I just implemented timer + auth checks to handle this in my app 😅

Does that stream also handling Play Games auth? Because I have some problems with handling it manually (even with timers):
0) User is not logged into google account on the device
1) Start app
2) Request sign in
3) System window will be opened -> sign in
4) Back to the app `isSignedIn` function does not return `true`

**Comment by theLee3** [comment]
@theRealGetman To be clear, I am in agreement about the extra auth calls. In the update, extra auth calls are handled gracefully in the package returning an error if previously called and not signed in.

The player stream works for GameCenter and Play Games. It should also fix the issue you are having with your current implementation, as `signIn` should no longer return before completed, ensuring that `isSignedIn`'s value will be correct.

**Comment by theRealGetman** [comment]
@theLee3 great! thank you!
When do you plan to release that version with streams to the main channel?

**Comment by theLee3** [comment]
It is available via `GameAuth.player`. `GamesServices` is a legacy monolithic class that is only still around to not break previous uses. The preferred usage is now the specialized classes: `GameAuth`, `Leaderboards`, `Achievements`, `SaveGame`. That being said, as it does still exist, I will provide the stream from `GamesServices` as well.

Afterwards, I will submit a PR. Then we can expect a release to pub.dev in a week or less.

**Comment by theRealGetman** [comment]
@theLee3 thank you for support ♥️

**Comment by theRealGetman** [comment]
Hey @theLee3 
I've checked your solution with Stream, but it doesn't work - stream doesn't emit after user logged in to GameCenter.

In the code snippet you can see that I tried with Stream and with a Timer + another package for GameCenter authorization.
Stream solution doesn't work and even `GamesServices.isSignedIn` inside timer also return `false` even when user is signed in, but Timer with another package return `true` when user is signed in and everything works.

```dart
/// Starts a stream that checks if the user is signed in with Game Services.
  void _startGameServiceCheck(BuildContext context) {
    _gameServiceCheck?.cancel();
    _gameServiceCheck = context.read<GamesService>().isSignedInStream.listen(
      (isSignedIn) {
        debugPrint('>>> isSignedIn: $isSignedIn');
        if (isSignedIn) {
          _stopGameServiceCheck();
          if (mounted) {
            context.dismissDialog();
            context.read<DashboardCubit>().onLogin();
          }
        }
      },
    );

    _gameServiceCheckTimer?.cancel();
    _gameServiceCheckTimer =
        Timer.periodic(const Duration(seconds: 1), (_) async {
      final isSignedIn =
          await GameServicesFirebaseAuth().isAlreadySignInWithGameService();
      debugPrint('>>> TIMER isSignedIn: $isSignedIn');
      if (isSignedIn) {
        _stopGameServiceCheck();
        if (mounted) {
          await context.dismissDialog();
          await context.read<DashboardCubit>().onLogin();
        }
      }
    });
  }
```

**Comment by theLee3** [comment]
On iOS, be sure to call `GameAuth.signIn()`. To maintain the same behavior the some devs expect from the package, this is still required. However, this need may be eliminated alongside the release of this update, and the package move to true auto sign-in on iOS.

**Comment by theLee3** [comment]
There may also be a conflict if you are signing into Game Center through both packages as they will both be setting the native auth handler for the app.

**Comment by theLee3** [comment]
@theRealGetman Can you provide anymore feedback on this? The PR is merged, and we certainly want to make sure everything is working before publishing.

**Comment by theRealGetman** [comment]
@theLee3  you can try to test it yourself, it's easy 😁:
1) Launch app, request login
2) Cancel login, start stream
3) Go to GameCenter in system settings and log in
4) Come back to the app

For me the stream is not updated with a new logged in state

**Comment by theLee3** [comment]
@theRealGetman Please try the latest `add-player-stream` branch and ensure that the issue is resolved.

**Comment by theLee3** [comment]
I was not seeing it previously because I was listening before the `signIn` call, and the listener was never disposed or recreated, which is what leads to the issue. Once all subs were cancelled, new subs would not receive updates. This could be caused by using any of the legacy methods or a `StreamBuilder` in a widget that disposed.

Rookie mistake 😳

**Comment by theRealGetman** [comment]
hey @theLee3 
yes, not it works with latest version from  add-player-stream branch and if I use only this package to try to log in :)
